//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichalZawadzkiLibrus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupSet
    {
        public GroupSet()
        {
            this.StudentSet = new HashSet<StudentSet>();
            this.LessonSet = new HashSet<LessonSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Term { get; set; }
        public string Place { get; set; }
        public Nullable<int> Teacher_Id { get; set; }
    
        public virtual ICollection<StudentSet> StudentSet { get; set; }
        public virtual ICollection<LessonSet> LessonSet { get; set; }
        public virtual TeacherSet TeacherSet { get; set; }
    }
}
