//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichalZawadzkiLibrus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkSet
    {
        public int Id { get; set; }
        public double Score { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Task_Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
    
        public virtual StudentSet StudentSet { get; set; }
        public virtual TaskSet TaskSet { get; set; }
    }
}
