//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichalZawadzkiLibrus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvaluationSystemEntities : DbContext
    {
        public EvaluationSystemEntities()
            : base("name=EvaluationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupSet> GroupSet { get; set; }
        public virtual DbSet<LessonSet> LessonSet { get; set; }
        public virtual DbSet<MarkSet> MarkSet { get; set; }
        public virtual DbSet<PresenceSet> PresenceSet { get; set; }
        public virtual DbSet<StudentSet> StudentSet { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaskSet> TaskSet { get; set; }
        public virtual DbSet<TeacherSet> TeacherSet { get; set; }
    }
}
