//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichalZawadzkiLibrus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSet
    {
        public StudentSet()
        {
            this.MarkSet = new HashSet<MarkSet>();
            this.PresenceSet = new HashSet<PresenceSet>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public Nullable<int> Group_Id { get; set; }
    
        public virtual GroupSet GroupSet { get; set; }
        public virtual ICollection<MarkSet> MarkSet { get; set; }
        public virtual ICollection<PresenceSet> PresenceSet { get; set; }
    }
}
