//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichalZawadzkiLibrus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskSet
    {
        public TaskSet()
        {
            this.MarkSet = new HashSet<MarkSet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> Lesson_Id { get; set; }
    
        public virtual LessonSet LessonSet { get; set; }
        public virtual ICollection<MarkSet> MarkSet { get; set; }
    }
}
